# Generated by Django 5.0.6 on 2024-12-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotate", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="desccription",
            new_name="description",
        ),
        migrations.AlterField(
            model_name="annotation",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
