# Generated by Django 5.0.6 on 2024-12-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotate", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="data",
            field=models.JSONField(null=True),
        ),
    ]
