# Generated by Django 5.0.6 on 2024-12-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotate", "0002_alter_annotation_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
