# Generated by Django 5.0.6 on 2024-12-18 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annotate", "0003_alter_annotation_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="desccription",
            new_name="description",
        ),
    ]
